import type { Config } from "tailwindcss";

// Design tokens copied verbatim from DESIGN.md (Stitch export) so the
// implementation stays pixel-consistent with the source design system.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#005049",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#006a61",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "outline-variant": "#bcc9c6",
        "inverse-primary": "#6bd8cb",
        "secondary-container": "#39b8fd",
        "on-secondary-fixed-variant": "#004c6e",
        "error-container": "#ffdad6",
        "secondary-fixed": "#c9e6ff",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#f5fff6",
        "tertiary-container": "#00855b",
        "on-secondary-container": "#004666",
        "on-primary-container": "#f4fffc",
        "tertiary": "#006947",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "on-surface": "#0b1c30",
        "outline": "#6d7a77",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#6bd8cb",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#89ceff",
        "primary-container": "#008378",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#005236",
        "secondary": "#006591",
        "primary-fixed": "#89f5e7",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001e2f",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-surface-variant": "#3d4947",
        "primary": "#00685f",
        "on-primary-fixed": "#00201d",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "2.5rem",
        "nav-rail-expanded": "240px",
        "container-margin": "2rem",
        "nav-rail-width": "80px",
        "gutter": "1.5rem",
        "card-padding": "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-md": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "title-lg": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      backdropBlur: {
        glass: "16px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
